### PR TITLE
Fixes to run on 1.9

### PR DESCRIPTION
**Pull request by erikh**
- FasterCSV cannot be used on 1.9
- You assume LogstashCli has been declared already as a module, which doesn't seem to happen in 1.9 (for some reason I didn't bother to find out why)

### CODE REVIEW

**Comment by jedi4ever** [comment]
thank you for these fixes! I primarily use ruby-1.8 in production so had not tested it onn 1.9

**Comment by erikh** [comment]
Any chance I could get you to cut another release soon? We're using it with a team of developers.

**Comment by erikh** [comment]
Thanks for the merge, too.

**Comment by jedi4ever** [comment]
New version released just now, have fun with it.

**Pull request merged**
