### PR TITLE
Allow more specific time range specification.

### PR DESCRIPTION
**Pull request by stevendanna**
The --last parameter can now understand minutes, hours, days, weeks,
and years.  For example, the following commands are now valid:

```
logstash-cli grep --last 15min foo
logstash-cli grep --last 10hrs foo
logstash-cli grep --last 1year foo
```

The --from and --to parameters can now optionally take a precise time
specification.  For example, the following command is now valid:

```
logstash-cli grep --from "2012-12-02" --to "2012-12-04 12:00:00"
```

### CODE REVIEW

**Comment by jedi4ever** [comment]
@stevendanna great! Can you also update the documentation with the new functionality?

**Comment by stevendanna** [comment]
Will do.  I'll push another update sometime this afternoon.

**Comment by stevendanna** [comment]
Readme updated.

**Comment by jedi4ever** [comment]
A great thank you @stevendanna !

**Pull request merged**
